INSERT INTO SHOP (SHOPID, SHOPDESC) VALUES (1, 'Colruyt');
INSERT INTO SHOP (SHOPID, SHOPDESC) VALUES (2, 'Delhaize');
INSERT INTO SHOP (SHOPID, SHOPDESC) VALUES (3, 'Match');
INSERT INTO SHOP (SHOPID, SHOPDESC) VALUES (4, 'Carrefour');
INSERT INTO SHOP (SHOPID, SHOPDESC) VALUES (5, 'Lidl');
INSERT INTO SHOP (SHOPID, SHOPDESC) VALUES (6, 'Aldi');